[package]
name = "supercharged-dhbw-integraluminium"
version = "3.4.1"
entrypoint = "lib.typ"
authors = ["Danny Seidel <@DannySeidel>"]
license = "MIT"
description = "Unofficial Template for DHBW"
repository = "https://github.com/Integraluminium/supercharged-typst-template"
keywords = ["dhbw", "thesis"]
categories = ["paper", "thesis", "report"]
exclude = ["examples/**", "CHANGELOG.md"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"